#Declared Name
name: First WorkFlow

#Event
on: push #workflow_dispatch, pullrequest

#WORKFLOW
jobs:
  #job name first-job
  first-job:
    #runner:-this is a container env that runs our code. Git hub runs it.
    runs-on: ubuntu-latest #other runners. MacOs, linux, Windows
    steps:
      #action 1
      - name: checkout changes
        run : actions/checkout@v4
      #action 2        
      - name: print greet
        run : echo "hello world!"
      #action 3
      - name: Print GOODBYE
        run : echo "DONE_BYE"