name: First WorkFlow

on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greet
        run: echo "hello world!"
      - name: Print GOODBYE
        run: echo "DONE_BYE"
      
